name: Build Kernel GKI 5.10 Official

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: 'Custom Kernel Name (Biarkan kosong untuk default)'
        required: false
        default: ''
        type: string
      clang_version:
        description: 'Pilih Versi Clang'
        required: true
        type: choice
        options:
          - 'r536225 (Clang 19)'
          - 'r547379 (Clang 20)'
      hook_method:
        description: 'Pilih Hook Method'
        required: true
        type: choice
        default: 'susfs'
        options:
          - 'susfs'
          - 'kprobes'

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Free disk space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "zixine"
          git config --global user.email "waheid005@gmail.com"

      - name: Install build tools
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y git curl repo build-essential bc bison flex libssl-dev \
            libelf-dev python3 python3-pip unzip zip rsync libncurses-dev lld

      - name: Init & Sync GKI
        run: |
          mkdir gki && cd gki
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10 --depth=1
          repo sync -c --no-tags --no-clone-bundle --optimized-fetch -j$(nproc --all)

      - name: Setup Upstream Rama update 
        working-directory: gki/common
        run: |
          git remote remove rama > /dev/null 2>&1 || true
          git remote add rama https://github.com/ramabondanp/android_kernel_common-5.10.git
          git fetch -j12 rama android12-5.10-staging
          git checkout -f -B update-5.10.247 rama/android12-5.10-staging

      - name: Tweak build config
        run: |
          sed -i '2d' gki/common/build.config.gki

      - name: Setup KernelSU-Next & Hook Method
        working-directory: gki/common
        run: |
          echo "üß© Setup KernelSU-Next dan Hook Method"
          
          # Hapus driver lama jika ada
          for KSU_PATH in drivers/staging/kernelsu drivers/kernelsu KernelSU; do
            if [ -d $KSU_PATH ]; then
              KSU_DIR=$(dirname "$KSU_PATH")
              [ -f "$KSU_DIR/Kconfig" ] && sed -i '/kernelsu/d' $KSU_DIR/Kconfig
              [ -f "$KSU_DIR/Makefile" ] && sed -i '/kernelsu/d' $KSU_DIR/Makefile
              rm -rf $KSU_PATH
            fi
          done
          
          # 1. Install sukisu Base
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s main
          
          HOOK_METHOD="${{ github.event.inputs.hook_method }}"
          
          if [ "$HOOK_METHOD" = "susfs" ]; then
            echo "‚û°Ô∏è Menambahkan SUSFS support ke KernelSU-Next"
            # 2. Install SUSFS Support via SukiSU
            curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
            
            # 3. Clone manual patch susfs (PENTING untuk visibility fix)
            git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android12-5.10 sus
            cp -r sus/kernel_patches/fs .
            cp -r sus/kernel_patches/include .
            patch -p1 < sus/kernel_patches/50_add_susfs_in_gki-android12-5.10.patch
            
            # Visibility fix untuk kernel 5.10
            sed -i '1i#include <linux/stat.h>' include/linux/susfs.h
            echo "‚úÖ SUSFS patched"
          fi

      - name: Fix Stack Protector
        working-directory: gki/common
        run: |
          sed -i '/config STACKPROTECTOR_PER_TASK/{n;s/def_bool y/bool "Stack Protector per task"\n\tdefault y/;}' arch/arm64/Kconfig
          echo "# CONFIG_STACKPROTECTOR_PER_TASK is not set" >> arch/arm64/configs/gki_defconfig

      - name: Patch module & DRM (Xiaomi Compat)
        working-directory: gki/common
        run: |
          sed -i '/pr_warn.*disagrees about version of symbol.*/,+1 s/.*/return 1;/' kernel/module.c
          sed -i '/^static int drm_atomic_check_valid_clones/,/^}/d' drivers/gpu/drm/drm_atomic_helper.c
          sed -i '/ret = drm_atomic_check_valid_clones/,/return ret;/d' drivers/gpu/drm/drm_atomic_helper.c

      - name: Inject All Kernel Configs
        working-directory: gki/common
        run: |
          DEFCONFIG="arch/arm64/configs/gki_defconfig"
          HOOK_METHOD="${{ github.event.inputs.hook_method }}"
          
          cat >> $DEFCONFIG <<EOF
          # KSU NEXT CONFIG
          CONFIG_KSU=y
          CONFIG_KPM=y
          CONFIG_KSU_SUSFS_SUS_SU=n
          CONFIG_KSU_INLINE_HOOK=y
          CONFIG_KSU_INLINE_HOOK_TRAMPOLINE=y
          CONFIG_KSU_INLINE_HOOK_TRAMPOLINE_SIZE=64
          CONFIG_KSU_INLINE_HOOK_MANAGER_ONLY=y
          CONFIG_KSU_INLINE_HOOK_WITH_KSU_PATCH=y
          EOF
          
          if [ "$HOOK_METHOD" = "susfs" ]; then
            cat >> $DEFCONFIG <<EOF
          CONFIG_KSU_SYSCALL_HOOK=n
          CONFIG_KSU_KPROBES_HOOK=n
          CONFIG_KSU_SUSFS=y
          CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_PATH=y
          CONFIG_KSU_SUSFS_SUS_MOUNT=y
          CONFIG_KSU_SUSFS_SUS_KSTAT_SPOOF_GENERIC=y
          CONFIG_KSU_SUSFS_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSTAT=y
          CONFIG_KSU_SUSFS_TRY_UMOUNT=y
          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
          CONFIG_KSU_SUSFS_ENABLE_LOG=y
          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
          EOF
          else
            echo "CONFIG_KSU_SYSCALL_HOOK=y" >> $DEFCONFIG
            echo "CONFIG_KSU_KPROBES_HOOK=y" >> $DEFCONFIG
            echo "CONFIG_KSU_SUSFS=n" >> $DEFCONFIG
          fi
          
          cat >> $DEFCONFIG <<EOF
          CONFIG_TMPFS_XATTR=y
          CONFIG_TMPFS_POSIX_ACL=y
          CONFIG_TCP_CONG_BBR=y
          CONFIG_DEFAULT_BBR=y
          CONFIG_HZ_300=y
          CONFIG_ZRAM=y
          EOF

      - name: Set version
        working-directory: gki/common
        run: |
          echo "" > scripts/setlocalversion
          KERNEL_NAME="${{ github.event.inputs.kernel_name }}"
          HOOK_METHOD="${{ github.event.inputs.hook_method }}"
          SUFFIX=$(echo "$HOOK_METHOD" | tr '[:lower:]' '[:upper:]')
          if [ -n "$KERNEL_NAME" ]; then
             sed -i "s/^EXTRAVERSION *=.*/EXTRAVERSION = -$KERNEL_NAME-$SUFFIX/" Makefile || echo "EXTRAVERSION = -$KERNEL_NAME-$SUFFIX" >> Makefile
          fi

      - name: Setup Clang
        working-directory: gki
        run: |
          mkdir -p prebuilts-master/clang/host/linux-x86
          if [ "${{ github.event.inputs.clang_version }}" == "r536225 (Clang 19)" ]; then
            CLANG_VER="clang-r536225"
            CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main-kernel-2025/clang-r536225.tar.gz"
          else
            CLANG_VER="clang-r547379"
            CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/62cdcefa89e31af2d72c366e8b5ef8db84caea62/clang-r547379.tar.gz"
          fi
          mkdir -p prebuilts-master/clang/host/linux-x86/$CLANG_VER
          curl -L "${CLANG_URL}" | tar -xz -C prebuilts-master/clang/host/linux-x86/$CLANG_VER
          ln -sf $CLANG_VER prebuilts-master/clang/host/linux-x86/clang-r416183b

      - name: Compile
        working-directory: gki
        run: |
          sed -i 's/check_defconfig//' common/build.config.gki
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh

      - name: Apply KPM Patch
        run: |
          IMG_PATH="gki/out/android12-5.10/common/arch/arm64/boot/Image"
          if [ -f "$IMG_PATH" ]; then
            cd $(dirname $IMG_PATH)
            curl -LSs "https://github.com/SukiSU-Ultra/SukiSU_patch/raw/refs/heads/main/kpm/patch_linux" -o patch
            chmod +x patch
            ./patch && [ -f oImage ] && mv -f oImage Image
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Upstream-5.10.247-${{ github.event.inputs.hook_method }}
          path: gki/out/android12-5.10/common/arch/arm64/boot/Image
