
name: 2 Suki Latest

on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: 'Custom Kernel Name (Leave empty for default)'
        required: false
        default: ''
        type: string
      clang_version:
        description: 'Select Clang Version'
        required: true
        type: choice
        options:
          - 'r536225 (Clang 19)'
          - 'r547379 (Clang 20)'

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          swap-size-mb: 10240
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Setup git identity
        run: |
          git config --global user.name "zixine"
          git config --global user.email "waheid005@gmail.com"
      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y git curl repo build-essential bc bison flex libssl-dev \
            libelf-dev python3 python3-pip unzip zip rsync libncurses-dev lld
      - name: Create and Init GKI Source (Shallow)
        run: |
          mkdir gki && cd gki
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10 --depth=1
          repo sync -c --no-tags --no-clone-bundle --optimized-fetch -j$(nproc --all)
      - name: Apply Rama Cherry-Pick (881fa16)
        run: |
          cd gki/common
          echo "Downloading commit 881fa16..."
          curl -L "https://github.com/ramabondanp/android_kernel_common-5.10/commit/881fa16.patch" -o rama.patch
          
          echo "Attempting git am..."
          if git am -3 < rama.patch; then
            echo "git am succeeded."
          else
            echo "git am failed. Aborting and falling back to force patch..."
            git am --abort
            
            # Apply patch, allow partial failure (skipped hunks are fine)
            patch -p1 --fuzz=3 < rama.patch || true
            
            echo "Applied via patch -p1 (Conflicts/Duplicates ignored)."
          fi
          rm rama.patch
      - name: Delete Line 2 in build.config.gki
        run: |
          sed -i '2d' gki/common/build.config.gki
      - name: Apply SukiSU Patch
        run: |
          cd gki/common
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s main
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
          git clone https://gitlab.com/simonpunk/susfs4ksu/ -b gki-android12-5.10 sus
          rm -rf sus/.git
          susfs=sus/kernel_patches
          cp -r $susfs/fs .
          cp -r $susfs/include .
          cp -r $susfs/50_add_susfs_in_gki-android12-5.10.patch .
          patch -p1 < 50_add_susfs_in_gki-android12-5.10.patch
      - name: Apply Extra Cherry-Picks
        working-directory: gki/common
        run: |
          echo "Applying requested cherry-picks..."
          
          # Patch 1: Common 5.10 update/fix
          curl -L "https://github.com/ramabondanp/android_kernel_common-5.10/commit/4fe04b60009e.patch" | git am -3 || {
             echo "git am failed, falling back to patch..."
             curl -L "https://github.com/ramabondanp/android_kernel_common-5.10/commit/4fe04b60009e.patch" | patch -p1
          }
      - name: Apply Manual Stack Protector Fix
        working-directory: gki/common
        run: |
          echo "ðŸ› ï¸ Applying manual Stack Protector fix based on screenshots..."
          # 1. Edit arch/arm64/Kconfig
          sed -i '/config STACKPROTECTOR_PER_TASK/{n;s/def_bool y/bool "Stack Protector per task"\n\tdefault y/;}' arch/arm64/Kconfig
          # 2. Disable di gki_defconfig
          echo "# CONFIG_STACKPROTECTOR_PER_TASK is not set" >> arch/arm64/configs/gki_defconfig
          
          echo "Stack Protector fix applied manually."
      - name: Apply inline patch for module.c and drm_atomic_helper.c
        run: |
          cd gki
          echo "patching module.c (change version mismatch to return 1)"
          sed -i '/pr_warn.*disagrees about version of symbol.*/,+1 s/.*/return 1;/' common/kernel/module.c
          
          echo "removing drm_atomic_check valid_clones"
          sed -i '/^static int drm_atomic_check_valid_clones/,/^}/d' common/drivers/gpu/drm/drm_atomic_helper.c
          
          echo "Removing drm_atomic_check_valid_clones call..."
          sed -i '/ret = drm_atomic_check_valid_clones/,/return ret;/d' common/drivers/gpu/drm/drm_atomic_helper.c
      - name: Remove check_defconfig
        run: |
          cd gki
          echo "[Clean-Up] Deleting check_defconfig"
          sed -i 's/check_defconfig//' ./common/build.config.gki
      - name: Fix KernelSU and sus directory state
        run: |
          cd gki/common
          rm -rf KernelSU/.git
          rm -rf sus/.git
          git rm --cached --ignore-unmatch -r KernelSU
          git rm --cached --ignore-unmatch -r sus
          git add KernelSU
          git add sus
          git commit -m "Inject KernelSU & SUSFS manually" || true
      - name: Add Custom Network & FS Configs
        run: |
          DEFCONFIG="gki/common/arch/arm64/configs/gki_defconfig"
          echo "Injecting custom configs to $DEFCONFIG"
          
          # --- KSU & KPM Configs ---
          echo "CONFIG_KSU=y" >> $DEFCONFIG
          echo "CONFIG_KPM=y" >> $DEFCONFIG
          # --- Custom Network & FS ---
          echo "CONFIG_TMPFS_XATTR=y" >> $DEFCONFIG
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> $DEFCONFIG
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> $DEFCONFIG
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> $DEFCONFIG
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> $DEFCONFIG
          echo "CONFIG_TCP_CONG_ADVANCED=y" >> $DEFCONFIG 
          echo "CONFIG_TCP_CONG_BBR=y" >> $DEFCONFIG
          echo "CONFIG_NET_SCH_FQ=y" >> $DEFCONFIG
          echo "CONFIG_TCP_CONG_BIC=n" >> $DEFCONFIG
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> $DEFCONFIG
          echo "CONFIG_TCP_CONG_HTCP=n" >> $DEFCONFIG 
          echo "CONFIG_DEFAULT_BBR=y" >> $DEFCONFIG
      - name: Set Kernel EXTRAVERSION (Optional)
        run: |
          cd gki/common
          echo "" > scripts/setlocalversion
          chmod +x scripts/setlocalversion
          
          KERNEL_NAME="${{ github.event.inputs.kernel_name }}"
          if [ -n "$KERNEL_NAME" ]; then
             echo "Setting custom kernel name: $KERNEL_NAME"
             if grep -q '^EXTRAVERSION *=' Makefile; then
               sed -i "s/^EXTRAVERSION *=.*/EXTRAVERSION = -$KERNEL_NAME/" Makefile
             else
               echo "EXTRAVERSION = -$KERNEL_NAME" >> Makefile
             fi
          else
             echo "Kernel name input is empty. Skipping custom name (Using Default)."
          fi
      - name: Append CONFIG_HZ_500 to defconfig
        run: |
          echo -e '\nCONFIG_HZ_500=y\nCONFIG_HZ=500' >> gki/common/arch/arm64/configs/gki_defconfig
      - name: Setup Custom Clang
        working-directory: gki
        run: |
          mkdir -p prebuilts-master/clang/host/linux-x86
          
          if [ "${{ github.event.inputs.clang_version }}" == "r536225 (Clang 19)" ]; then
            echo "Setting up Clang-19 (r536225)..."
            CLANG_VER="clang-r536225"
            CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main-kernel-2025/clang-r536225.tar.gz"
          else
            echo "Setting up Clang-20 (r547379)..."
            CLANG_VER="clang-r547379"
            CLANG_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/62cdcefa89e31af2d72c366e8b5ef8db84caea62/clang-r547379.tar.gz"
          fi
          
          echo "CLANG_VER=$CLANG_VER" >> $GITHUB_ENV
          mkdir -p prebuilts-master/clang/host/linux-x86/$CLANG_VER
          cd prebuilts-master/clang/host/linux-x86
          curl -L "${CLANG_URL}" | tar -xz -C $CLANG_VER
          
          rm -rf clang-r416183b
          ln -sf $CLANG_VER clang-r416183b
      - name: Final Clean Tree Commit
        run: |
          cd gki/common
          git add .
          git commit -m "Final clean tree before build" || true
      - name: Build Kernel
        run: |
          cd gki
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
      - name: Apply KPM Patch
        run: |
          cd gki/out/android12-5.10/common/arch/arm64/boot/
          if [ -f Image ]; then
            echo "Image found, applying KPM patch..."
            curl -LSs "https://github.com/SukiSU-Ultra/SukiSU_patch/raw/refs/heads/main/kpm/patch_linux" -o patch
            chmod 777 patch
            ./patch
            if [ -f oImage ]; then
              mv -f oImage Image
              ls -lh Image
            else
              echo "Error: oImage not found!"
              exit 1
            fi
          else
            echo "Image file not found. Skipping KPM patch."
          fi
      - name: Upload Kernel Image to GitHub Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zixine-image
          path: gki/out/android12-5.10/common/arch/arm64/boot/Image
          if-no-files-found: warn

      - name: Upload Image to PixelDrain
        if: always() 
        run: |
          if [ -f gki/out/android12-5.10/common/arch/arm64/boot/Image ]; then
            curl -u :dc8dc353-bb1c-4f52-806d-000961e53f1a \
              -F file=@gki/out/android12-5.10/common/arch/arm64/boot/Image \
              https://pixeldrain.com/api/file
          else
            echo "Image file not found. Build failed."
          fi
